project:
  type: website

website:
  title: "Course Template"
  navbar:
    logo: /img/logo.png
    left:
      - href: index.qmd
        text: Introduction
    right: 
      - icon: github
        href: https://github.com/hds-sandbox/scverse-2024-workshop
        aria-label: GitHub
      

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
    code-fold: true
