project:
  type: website

website:
  title: "Projections and interactive plots for Single Cell data analysis"
  navbar:
    logo: /img/logo.png
    left:
      - href: index.qmd
        text: Welcome
      - href: publish.qmd
        text: Publish
      - href: notebooks/interactivePlotsTransc.ipynb
        text: Tutorial
    right: 
      - icon: github
        href: https://github.com/hds-sandbox/scverse-2024-workshop
        aria-label: GitHub
      

format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
